version: '3.8'

services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./infrastructure/framework/frontend:/app
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    env_file:
      - .env
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port ${FRONTEND_PORT}"
    depends_on:
      - backend

  backend:
    image: denoland/deno:alpine
    volumes:
      - .:/app
    working_dir: /app/infrastructure/framework/backend
    command: deno task start
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  pgdata:
